apiVersion: v1
kind: ConfigMap
metadata:
  name: lifesub-common-config
  namespace: dg0409-lifesub-ns
data:
  ALLOWED_ORIGINS: "http://4.217.130.141"
  JPA_DDL_AUTO: "update"
  JPA_SHOW_SQL: "true"
  LOGGING_LEVEL_UNICORN: "DEBUG"
  LOGGING_LEVEL_HIBERNATE_SQL: "TRACE"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
  namespace: dg0409-lifesub-ns
data:
  SERVER_PORT: "8081"
  POSTGRES_HOST: "postgres-member-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "member"
  JWT_ACCESS_TOKEN_VALIDITY: "3600000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysub-config
  namespace: dg0409-lifesub-ns
data:
  SERVER_PORT: "8082"
  POSTGRES_HOST: "postgres-mysub-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mysub"
  FEE_LEVEL_COLLECTOR: "50000"
  FEE_LEVEL_ADDICT: "100000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recommend-config
  namespace: dg0409-lifesub-ns
data:
  SERVER_PORT: "8083"
  POSTGRES_HOST: "postgres-recommend-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "recommend"
