apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend
  namespace: dg0409-lifesub-ns
  labels:
    app: recommend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommend
  template:
    metadata:
      labels:
        app: recommend
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: recommend
        image: acrdigitalgarage02.azurecr.io/dg0409/recommend:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: recommend-config
              key: SERVER_PORT
        envFrom:
        - configMapRef:
            name: lifesub-common-config
        - configMapRef:
            name: recommend-config
        - secretRef:
            name: lifesub-secret
